# PLEASE NOTE: Travis is not currently utilised by the Moodle core integration
# process (which uses our internal CI system) this file is here for the benefit
# of community developers git clones - see MDL-51458.

# We currently disable Travis notifications entirely until https://github.com/travis-ci/travis-ci/issues/4976
# is fixed.
notifications:
  email: false

language: php

os: linux

dist: xenial

services:
  - mysql
  - docker

addons:
  postgresql: "9.6"

jobs:
    # Enable fast finish.
    # This will fail the build if a single job fails (except those in allow_failures).
    # It will not stop the jobs from running.
    fast_finish: true

    include:
      # CI Tests are always against lowest, and heighest supported versions of PHP.
      - php: 7.2
        env: DB=pgsql   TASK=CITEST
      - php: 7.4
        env: DB=pgsql   TASK=CITEST

      # PHPUnit with Postgres against lowest, and highest supported versions of PHP.
      - php: 7.2
        env: DB=pgsql   TASK=PHPUNIT
      - php: 7.4
        env: DB=pgsql   TASK=PHPUNIT

      # PHPUnit with MySQLi against highest version of PHP only.
      - php: 7.4
        env: DB=mysqli  TASK=PHPUNIT

      # Upgrade test is always against the lowest supported version of php.
      - php: 7.2
        env: DB=mysqli  TASK=UPGRADE

      # Run grunt/npm tasks against any version of PHP.
      - php: 7.4
        env: DB=none  TASK=GRUNT

cache:
    directories:
      - $HOME/.composer/cache
      - $HOME/.npm

before_install: ./.travis/before_install.sh
install: ./.travis/install.sh
before_script: ./.travis/before_script.sh
script: ./.travis/script.sh
after_script: ./.travis/after_script.sh
