# PLEASE NOTE: Travis is not currently utilised by the Moodle core integration
# process (which uses our internal CI system) this file is here for the benefit
# of community developers git clones - see MDL-51458.

# We currently disable Travis notifications entirely until https://github.com/travis-ci/travis-ci/issues/4976
# is fixed.
notifications:
  email: false

language: php

os: linux

dist: xenial

services:
    - mysql
    - docker

php:
    # We only run the highest and lowest supported versions to reduce the load on travis-ci.org.
    - 7.4

script:
    - echo "============================================================================"
    - echo "/etc/profile"
    - cat /etc/profile
    - echo "============================================================================"
    - echo "/etc/bash.bashrc"
    - cat /etc/bash.bashrc
    - echo "============================================================================"
    - echo "$HOME/.bashrc"
    - cat $HOME/.bashrc
    - echo "============================================================================"
    - echo "$BASH_ENV"
    - cat $BASH_ENV
    - echo "============================================================================"
    - echo /home/travis/.travis/job_stages
    - cat /home/travis/.travis/job_stages
    - echo "============================================================================"
